-- Milk quality screening Supabase schema.

CREATE TABLE IF NOT EXISTS society_month_stats (
    id BIGSERIAL PRIMARY KEY,
    facility TEXT NOT NULL,
    dcs DOUBLE PRECISION NOT NULL,
    society_name TEXT,
    file_year INTEGER NOT NULL,
    file_month INTEGER NOT NULL,
    season TEXT NOT NULL,
    record_count INTEGER NOT NULL,
    morning_count INTEGER,
    evening_count INTEGER,
    low_qty_count INTEGER,
    high_snf_spike_count INTEGER,
    fat_pct_mean DOUBLE PRECISION,
    fat_pct_std DOUBLE PRECISION,
    fat_pct_median DOUBLE PRECISION,
    fat_pct_q1 DOUBLE PRECISION,
    fat_pct_q3 DOUBLE PRECISION,
    fat_pct_p90 DOUBLE PRECISION,
    fat_pct_p10 DOUBLE PRECISION,
    fat_pct_min DOUBLE PRECISION,
    fat_pct_max DOUBLE PRECISION,
    snf_pct_mean DOUBLE PRECISION,
    snf_pct_std DOUBLE PRECISION,
    snf_pct_median DOUBLE PRECISION,
    snf_pct_q1 DOUBLE PRECISION,
    snf_pct_q3 DOUBLE PRECISION,
    snf_pct_p90 DOUBLE PRECISION,
    snf_pct_p10 DOUBLE PRECISION,
    snf_pct_min DOUBLE PRECISION,
    snf_pct_max DOUBLE PRECISION,
    clr_mean DOUBLE PRECISION,
    clr_std DOUBLE PRECISION,
    clr_median DOUBLE PRECISION,
    clr_q1 DOUBLE PRECISION,
    clr_q3 DOUBLE PRECISION,
    clr_p90 DOUBLE PRECISION,
    clr_p10 DOUBLE PRECISION,
    clr_min DOUBLE PRECISION,
    clr_max DOUBLE PRECISION,
    qty_mean DOUBLE PRECISION,
    qty_std DOUBLE PRECISION,
    qty_median DOUBLE PRECISION,
    qty_q1 DOUBLE PRECISION,
    qty_q3 DOUBLE PRECISION,
    qty_p90 DOUBLE PRECISION,
    qty_p10 DOUBLE PRECISION,
    qty_min DOUBLE PRECISION,
    qty_max DOUBLE PRECISION,
    filename TEXT,
    processed_at TIMESTAMPTZ,
    parser_warning_count INTEGER DEFAULT 0,
    UNIQUE(facility, dcs, file_year, file_month)
);

CREATE TABLE IF NOT EXISTS society_baselines (
    id BIGSERIAL PRIMARY KEY,
    facility TEXT NOT NULL,
    dcs DOUBLE PRECISION NOT NULL,
    society_name TEXT,
    season TEXT NOT NULL,
    record_count INTEGER NOT NULL,
    prior_month_count INTEGER,
    same_season_prior_month_count INTEGER,
    eligible BOOLEAN DEFAULT FALSE,
    fat_pct_mean DOUBLE PRECISION,
    fat_pct_std DOUBLE PRECISION,
    fat_pct_median DOUBLE PRECISION,
    fat_pct_q1 DOUBLE PRECISION,
    fat_pct_q3 DOUBLE PRECISION,
    fat_pct_p90 DOUBLE PRECISION,
    fat_pct_p10 DOUBLE PRECISION,
    snf_pct_mean DOUBLE PRECISION,
    snf_pct_std DOUBLE PRECISION,
    snf_pct_median DOUBLE PRECISION,
    snf_pct_q1 DOUBLE PRECISION,
    snf_pct_q3 DOUBLE PRECISION,
    snf_pct_p90 DOUBLE PRECISION,
    snf_pct_p10 DOUBLE PRECISION,
    clr_mean DOUBLE PRECISION,
    clr_std DOUBLE PRECISION,
    clr_median DOUBLE PRECISION,
    clr_q1 DOUBLE PRECISION,
    clr_q3 DOUBLE PRECISION,
    clr_p90 DOUBLE PRECISION,
    clr_p10 DOUBLE PRECISION,
    qty_mean DOUBLE PRECISION,
    qty_std DOUBLE PRECISION,
    qty_median DOUBLE PRECISION,
    qty_q1 DOUBLE PRECISION,
    qty_q3 DOUBLE PRECISION,
    qty_p90 DOUBLE PRECISION,
    qty_p10 DOUBLE PRECISION,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(facility, dcs, season)
);

CREATE TABLE IF NOT EXISTS flagged_anomalies (
    id BIGSERIAL PRIMARY KEY,
    facility TEXT NOT NULL,
    dcs DOUBLE PRECISION NOT NULL,
    society_name TEXT,
    date TEXT NOT NULL,
    shift TEXT NOT NULL,
    vehicle TEXT,
    qty DOUBLE PRECISION,
    fat_pct DOUBLE PRECISION,
    snf_pct DOUBLE PRECISION,
    clr DOUBLE PRECISION,
    z_snf DOUBLE PRECISION,
    z_fat DOUBLE PRECISION,
    z_clr DOUBLE PRECISION,
    z_qty DOUBLE PRECISION,
    rules_fired TEXT,
    diagnosis TEXT NOT NULL,
    confidence TEXT NOT NULL,
    explanation TEXT,
    seasonal_suppressed BOOLEAN DEFAULT FALSE,
    file_month INTEGER NOT NULL,
    file_year INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS month_summaries (
    id BIGSERIAL PRIMARY KEY,
    facility TEXT NOT NULL,
    file_month INTEGER NOT NULL,
    file_year INTEGER NOT NULL,
    records_processed INTEGER,
    societies_active INTEGER,
    initial_flags INTEGER,
    seasonal_suppressed INTEGER,
    final_flags INTEGER,
    high_confidence_flags INTEGER,
    top_diagnosis TEXT,
    top_flagged_societies JSONB,
    notes TEXT,
    mode TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(facility, file_month, file_year)
);

CREATE TABLE IF NOT EXISTS audit_trail (
    id BIGSERIAL PRIMARY KEY,
    facility TEXT,
    file_month INTEGER,
    file_year INTEGER,
    metric TEXT NOT NULL,
    value INTEGER,
    mode TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS report_bundles (
    id BIGSERIAL PRIMARY KEY,
    facility TEXT NOT NULL,
    file_month INTEGER NOT NULL,
    file_year INTEGER NOT NULL,
    mode TEXT NOT NULL,
    report_pdf_path TEXT,
    bundle_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(facility, file_month, file_year)
);

CREATE INDEX IF NOT EXISTS idx_month_stats_facility_dcs ON society_month_stats(facility, dcs);
CREATE INDEX IF NOT EXISTS idx_month_stats_month ON society_month_stats(file_year, file_month);
CREATE INDEX IF NOT EXISTS idx_baselines_facility_dcs ON society_baselines(facility, dcs, season);
CREATE INDEX IF NOT EXISTS idx_flagged_facility_date ON flagged_anomalies(facility, date);
CREATE INDEX IF NOT EXISTS idx_flagged_dcs ON flagged_anomalies(facility, dcs);
CREATE INDEX IF NOT EXISTS idx_summaries_month ON month_summaries(file_year, file_month);
CREATE INDEX IF NOT EXISTS idx_report_bundles_month ON report_bundles(file_year, file_month);
